// <auto-generated />
namespace Blog.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cc4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cc4));
        
        string IMigrationMetadata.Id
        {
            get { return "201903221224389_cc4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
