SET IDENTITY_INSERT [dbo].[Posts] ON
INSERT INTO [dbo].[Posts] ([PostId], [Title], [ShortDetail], [PostDate], [PostStatus], [ViewCount], [TitleImageData], [ImageMimeType], [AuthorId], [IsFeatured]) VALUES (1, N'Güvenli Yazılım Geliştirme', N'Yazılımda Güvenlik', N'2019-03-20 00:00:00', 1, 0, <Binary Data>, N'image/jpeg', 1, 0)
INSERT INTO [dbo].[Posts] ([PostId], [Title], [ShortDetail], [PostDate], [PostStatus], [ViewCount], [TitleImageData], [ImageMimeType], [AuthorId], [IsFeatured]) VALUES (2, N'Yazılımda Abstraction Nedir?', N'Soyutlaştırma', N'2019-03-20 00:00:00', 1, 10, <Binary Data>, N'image/png', 1, 0)
INSERT INTO [dbo].[Posts] ([PostId], [Title], [ShortDetail], [PostDate], [PostStatus], [ViewCount], [TitleImageData], [ImageMimeType], [AuthorId], [IsFeatured]) VALUES (3, N'C'' de Makrolar', N'C'' de Makrolar', N'2019-03-20 00:00:00', 1, 12, <Binary Data>, N'image/png', 1, 1)
INSERT INTO [dbo].[Posts] ([PostId], [Title], [ShortDetail], [PostDate], [PostStatus], [ViewCount], [TitleImageData], [ImageMimeType], [AuthorId], [IsFeatured]) VALUES (4, N'Yapılar, Birlikler ve Bit Alanları', N'Yapılar, Birlikler ve Bit Alanları', N'2019-03-20 00:00:00', 1, 7, <Binary Data>, N'image/png', 1, 1)
INSERT INTO [dbo].[Posts] ([PostId], [Title], [ShortDetail], [PostDate], [PostStatus], [ViewCount], [TitleImageData], [ImageMimeType], [AuthorId], [IsFeatured]) VALUES (5, N'C ve OpenGL', N'C ve OpenGL', N'2019-03-04 00:00:00', 1, 6, <Binary Data>, N'image/png', 1, 0)
INSERT INTO [dbo].[Posts] ([PostId], [Title], [ShortDetail], [PostDate], [PostStatus], [ViewCount], [TitleImageData], [ImageMimeType], [AuthorId], [IsFeatured]) VALUES (6, N'NHibernate', N'NHibernate', N'2019-02-27 00:00:00', 1, 12, <Binary Data>, N'image/jpeg', 1, 1)
INSERT INTO [dbo].[Posts] ([PostId], [Title], [ShortDetail], [PostDate], [PostStatus], [ViewCount], [TitleImageData], [ImageMimeType], [AuthorId], [IsFeatured]) VALUES (1002, N'SharePoint 2010 – Tasarımın Düzenlenmesi', N'SharePoint', N'2019-03-25 00:00:00', 1, 7, <SQLVARIANT>, NULL, 1, 1)
SET IDENTITY_INSERT [dbo].[Posts] OFF
