SET IDENTITY_INSERT [dbo].[Comments] ON
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1, N'Yılmaz', N'Mustafa', N'çok teşekkürler emeğimize sağlık', N'2019-03-20 00:00:00', 2, 1, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (2, N'anil@gmail.com', N'Anıl', N'Çok Açıklayıcı bir makale', N'2019-03-20 00:00:00', 2, 1, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1002, N'Yılmaz', N'Mustafa', N'çok teşekkürler emeğimize sağlık', N'2019-03-20 00:00:00', 6, 0, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1003, N'anil@gmail.com', N'Anıl', N'Çok Açıklayıcı bir makale', N'2019-03-20 00:00:00', 6, 0, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1004, N'anil@gmail.com', N'Anıl', N'Çok Açıklayıcı bir makale xxx', N'2019-03-20 00:00:00', 6, 1, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1005, N'anil@gmail.com', N'Anıl', N'Çok Açıklayıcı bir makale xxx rr', N'2019-03-20 00:00:00', 6, 1, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1006, N'anil@gmail.com', N'Anıl', N'Çok Açıklayıcı bir makale', N'2019-03-20 00:00:00', 6, 1, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1007, N'Yılmaz', N'Mustafa', N'çok teşekkürler emeğimize sağlık', N'2019-03-20 00:00:00', 6, 1, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1008, N'Yılmaz', N'Mustafa', N'çok teşekkürler emeğimize sağlık', N'2019-03-20 00:00:00', 5, 0, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1009, N'Yılmaz', N'Mustafa', N'çok teşekkürler', N'2019-03-20 00:00:00', 6, 0, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1010, N'Yılmaz', N'Mustafa', N'çok teşekkürler emeğimize sağlık', N'2019-03-20 00:00:00', 6, 0, NULL, NULL)
INSERT INTO [dbo].[Comments] ([CommentId], [CommenterMail], [CommenterName], [Message], [CommentDate], [PostId], [Status], [RootId], [Comment_CommentId]) VALUES (1011, N'Yılma', N'Mustaf', N'çok ', N'2019-03-20 00:00:00', 5, 0, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Comments] OFF
